create table cliente (
    id bigint generated by default as identity, 
    idade int not null, 
    nome varchar(180) not null, 
    cpf varchar not null unique,
    data_nascimento date not null,
    primary key (id)
);